spring.application.name=location-service
server.port=8082
server.servlet.context-path=/locations

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/location_database
spring.datasource.username=rota-facil
spring.datasource.password=admin


# JPA + HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.log-resolvers=true

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.fetch-registry=true

# RABBIMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:rota-facil}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

# OBSERVABILITY
# traces
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# metrics
management.otlp.metrics.export.enabled=true 

# collector
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics