spring.application.name=location-service
server.port=8082

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/location_database
spring.datasource.username=rota-facil
spring.datasource.password=admin

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}5
eureka.client.fetch-registry=true